### ISSUE TITLE
Player stuck performing mask raising animation despite not holding the mask anymore

### ISSUE THREAD

**Issue by lxative** [OE100/PossessedMask#1]
Players often get stuck holding items to their face even when not holding the mask or after dropping the mask.

![stuck_animation](https://github.com/OE100/PossessedMask/assets/149924874/8beb7e11-7fe0-47e6-adee-bb0610544aec)

**Comment by OE100** [comment]
I'll look into it a bit later today, probably an animation trigger I forgot to turn off.

**Comment by OE100** [comment]
Should be fixed in version 1.0.6
