### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by Multiname** [OE100/PossessedMask#12]
![изображение_2024-01-26_163902329](https://github.com/OE100/PossessedMask/assets/36795381/bc3ac7f4-4150-4e49-8014-b2b6962b36af)
![изображение_2024-01-26_164021185](https://github.com/OE100/PossessedMask/assets/36795381/c68341c8-44fb-49a8-8894-a7752abb797e)

**Comment by OE100** [comment]
do you have the entire log file of this run?
I have a suspicion, but I can't know what caused it without it

**Comment by OE100** [comment]
did it happen right at the start of the game?

**Comment by Multiname** [comment]
The first error happened after a while when I picked up a mask and 3 other items. Then next errors happened when I set the mask in the active slot

**Comment by Multiname** [comment]
I tested it with my save, so yes, it was start of the game after landing

**Comment by Multiname** [comment]
[LogOutput.log](https://github.com/OE100/PossessedMask/files/14065980/LogOutput.log)

Here is log file

**Comment by OE100** [comment]
were you playing with other mods?

**Comment by Multiname** [comment]
Possessed_Masks v2.0.0
BepInExPack v5.4.2100
LCBetterSaves v1.7.3 (to get the save)

**Comment by OE100** [comment]
and were there other players playing?
also was it local or online?

**Comment by Multiname** [comment]
I was alone, launch mode is online

**Comment by OE100** [comment]
did you manage to recreate it? or was it a one time thing?
because theoretically it should never happen, I have checks in place to prevent this scenario

**Comment by Multiname** [comment]
I can recreate it. I can also try to send you the save where I test this

**Comment by OE100** [comment]
just give me the list of steps to recreate the issue and I'll do some further testing

**Comment by Multiname** [comment]
1. Load the save where I have masks and some scrap on the ship 
2. Land on the already selected moon
3. Pick up 3 scrap and a mask
4. Set the mask to an inactive slot
5. After a while the first error occurs
6. Set the mask to an active slot
7. After a while the second error occurs

After the first error occurred I also noticed, that if the mask is in an inactive slot then the second error occurs from time to time, else it will spam to the log as shown in the screenshot

**Comment by OE100** [comment]
I need some more specifics as I can't seem to replicate the bug.
Does it happen on any save you open?
Does it happen only with the specific scrap combination? (if so which scrap did you have in which slot)
What moon did it happen on?
Did you try deleting the config file to reset it? (maybe you put in a bad value as one of the settings which caused a crash)

**Comment by Chaulilou** [comment]
Hey just wanted to say I had the same issue with this build. However, reverting to 1.1.2, it suddenly worked. No clue what's going on. Best of luck to you ^^

Exported Mod List: 018d4a1c-1d53-3dd2-c51a-c4a4858ca00c

**Comment by Multiname** [comment]
Now I've tried the following:
1. Create a new profile in thunderstore
2. Get the mods:
* LCBetterSaves v1.7.3
* LethalDevMode v1.0.0
* Possessed_Masks v2.0.0
3. Load the game, create a new save
4. Land on already selected Experimentation
5. Using LethalDevMode spawn 3 big bolts and a tragedy 
6. Pick up these items
7. And as I said previously if the mask is in an inactive slot you get the first error and if it is in an active - the second one

**Comment by Multiname** [comment]
Speaking about the previous save where I tested this yesterday, I picked up common scrap like teakettle. On this save I have 0 days before the quota, the selected moon is Titan and I land on it.

**Comment by OE100** [comment]
@Multiname should be solved in version 2.0.1 which is now on github, should be up on thunderstore too in 30 mins tops.

if it isn't open an issue.

thanks for checking out my mod :)

**Comment by Multiname** [comment]
Okay, I'll test it. Glad you've returned to this mod, I had other issues, so I will check them too and write to you if I find something

**Comment by Multiname** [comment]
![изображение_2024-01-27_154125250](https://github.com/OE100/PossessedMask/assets/36795381/b56fa0c2-4ccd-4e15-aee8-75edc166975f)

Tested using the last sequence of steps

**Comment by Multiname** [comment]
![image](https://github.com/OE100/PossessedMask/assets/36795381/1f03daea-a0e3-43ac-b2b1-a57fe55e7e41)

I also found this. The same thing was in 2.0.0 but I though you noticed it in the logs
