### ISSUE TITLE
New problems with v2.0.2

### ISSUE THREAD

**Issue by Multiname** [OE100/PossessedMask#13]
Hi, it's me again. Now the slots are switching and the mask is trying to put on the face, but I found a couple more problems.

The first one is that I can drop a mask regardless how many slots are filled while the NumberOfSlotsFilledToEnableDroppingMask is set to 3. To recreate this I either load the save where I have masks and scrap, or start a new game and spawn a mask and scraps using LethalDevMode v1.0.0. The mods that I have at that moment are:
* Evaisa-HookGenPatcher-0.0.5
* BepInEx-BepInExPack-5.4.2100
* Evaisa-LethalLib-0.14.0
* OE_Tweaks-Possessed_Masks-2.0.2
* Pooble-LCBetterSaves-1.7.3
* megumin-LethalDevMode-1.0.0 (I even tried to disable it when tested the first method)

The second one is hard to recreate, at least I haven't found how to do it yet. Seems like if you switch a slot when the mod tries to do the same you get the following error and you will not be able to switch slots or interact with anything using E button:
![image](https://github.com/OE100/PossessedMask/assets/36795381/561b5b4c-2033-42d3-86b8-7d40c6a9a658)

I also found this, I don't know if it should be the way it is:
![image](https://github.com/OE100/PossessedMask/assets/36795381/158f9100-f925-4220-948c-b4a430b975f5)
The message appears when the mod switches a slot or tries to put on a mask.

**Comment by Multiname** [comment]
Okay, the problem with NumberOfSlotsFilledToEnableDroppingMask has been fixed in v2.0.3

**Comment by OE100** [comment]
yeah, and lethallib 0.14.0 was broken anyway
