### ISSUE TITLE
Option to only change scrap value of masks

### ISSUE THREAD

**Issue by PickeBlind** [OE100/PossessedMask#14]
Pretty much what the title says. The max I can do is set EnableChangeMaskSpawnChance to 1, but that changes spawn chance as well. I apologize if there is already a way of doing this.

**Comment by OE100** [comment]
Just to clarify: you want an option to change the value without changing the spawn chance of masks right?
I could add it in the next update if that's the case

**Comment by OE100** [comment]
Uploaded version 2.0.4 to the releases page of this github project @PickeBlind
