### ISSUE TITLE
Potential issue if updating from older versions

### ISSUE THREAD

**Issue by haroelim** [OE100/PossessedMask#15]
I've been using this mod for a while, and out of nowhere it stopped working around three days ago.

I thought that I maybe messed up the configs, so I checked it and noticed apparently two config files for this mod, "PossessedMask.cfg" and "PossessedMasks.cfg" (note the plural Masks)

I looked at an older profile, and noticed that the older profile only had "PossessedMask.cfg"

I deleted both config files, and launched the modded game again, and this time it worked. When I checked the config files, the current version of the mod only had "PossessedMasks.cfg" (The one that is plural)

I noticed that there is not mention of the config file change in the description

**Comment by OE100** [comment]
yeah, I did some refactoring between 1.x.x and 2.0.0, one of these changes is the behind the scenes name of the mod which is correlated to the config file.

I honestly didn't think about it when I made the new version so thanks for telling me.

That being said I don't think there's much I can do about it (apart from maybe adding it to the readme)
