### ISSUE TITLE
Issue with possession

### ISSUE THREAD

**Issue by Jking0101** [OE100/PossessedMask#17]
After a lot of testing and configuring in the CFG file I have noticed that when your slots eventually auto switch to the mask and the auto equip animation plays, you do not get possessed as I thought you would, you only get possessed if you keep holding onto the mask and then the auto animation plays again. The reason this is an issue, is because if players play seriously they will try to keep the mask out of their slot by scrolling away to another slot the whole time, and by chance if they don't succeed and they end up on the mask slot and the auto animation plays they then get possessed they at least tried not to if that makes sense. I am not sure if I did something wrong for me to experience this issue and if I did please assist me, I just thought I would contact the author to double check if I have found a bug or if I screwed up somehow.

**Comment by OE100** [comment]
the possession phase does work fine as far as I can see, even in testing and some videos that people sent me it's working fine.
it's just chance based (same as vanilla)
