### ISSUE TITLE
Bug with mask possession and items

### ISSUE THREAD

**Issue by Tiibberz** [OE100/PossessedMask#2]

**Comment by Tiibberz** [comment]
I don't know if this is the issue fixed in 1.0.7 with the animation breaking, but the bug I wanted to submit is that the mask possessing me with the ship in orbit made it so every other item was zoomed in into my face, like if I was putting on the mask, which made it impossible to see anything whenever I was holding most items.

**Comment by OE100** [comment]
Animation breaks should be solved in newer versions, I recommend the newest version
