### ISSUE TITLE
bug when interacting after possession

### ISSUE THREAD

**Issue by parakatins** [OE100/PossessedMask#3]
when the mask starts the possession animation (and you stop it), every time you try to interact with something in hand, you need to click several times for interaction to work (be it stairs, items, doors)

**Comment by OE100** [comment]
You shouldn't be able to interact with things during the possession animation, could you recall what steps you took to interact with objects during the possession stage?

**Comment by parakatins** [comment]
> You shouldn't be able to interact with things during the possession animation, could you recall what steps you took to interact with objects during the possession stage?

not when she tries to possess you(your character puts the mask on his face alone), but after the animation happens and you stop her by exchanging slots.
After that, even if you drop her, the problem of interacting starts to happen.

(and I'm sorry if I'm speaking a bit poorly, English is not my native language 😅)

**Comment by OE100** [comment]
There is definitely an issue with hotbarplus, I have been trying to think of a way to fix it but so far nothing works for me

**Comment by OE100** [comment]
I am adding a config option to disable some of the mod mechanics in version 1.1.0, for now it's not stable and only here on github

**Comment by parakatins** [comment]
> I am adding a config option to disable some of the mod mechanics in version 1.1.0, for now it's not stable and only here on github


conflict between mods is always inevitable, but thank you very much for your consideration ❤️

**Comment by jmanndev** [comment]
I had a similar issue.  I was carrying a 2 handed item, and the mask changed slot to my active slot.  Both the mask and 2handed item were rendered at the same time and from then on I wasn't able to interact with any thing (no interact prompt popups either) or change my active slot.  I eventually got possessed and died, and still wasn't able to interact with anything until I restarted the game.  It felt like I was stuck in the 'being possessed' state. The mask had already attempted to possess me twice before that run, but I'd managed to swap off it before it took over (I didn't have a 2h item then either).

Mods I use that affect inventory:
- ItemQuickSwitch
- ScrollInverter

I'm going to attempt to recreate it with TwoHandedItemBehaviour set to FALSE.  This occurred with the default setting of TRUE.

**Comment by OE100** [comment]
@jmanndev I'm not on my computer right now, but I'll try patching it tomorrow when I get the time, this might be solvable by a simple delay of the possession trigger

**Comment by jmanndev** [comment]
I did some more testing of it.  I think part of the issue is the mask didn't force me to drop the 2h item.  When I set the TwoHandedItemBehaviour config to FALSE it worked (took over my active slot and dropped the 2h).  So might have just been a config bug on my side.

**Comment by rogedkone** [comment]
Reserved Slots (Walki, flashlight) also broken after taking back in inv. Items in reserved slot cant charging

**Comment by OE100** [comment]
@jmanndev see the newer version, I hopefully fixed some edge cases.

@rogedkone I have no way to support reserved slots
