### ISSUE TITLE
cant drop mask (try push G)

### ISSUE THREAD

**Issue by rogedkone** [OE100/PossessedMask#6]
cant drop mask (try push G many many times)

Mods list:
LC_API
DanceTools (for debug)
HDMod

Config (can drop heavy(two handled) items: false) // because items disappear (still)

![image](https://github.com/OE100/PossessedMask/assets/85563010/66c5795a-8dff-4d8b-95ef-d610c167835d)

**Comment by OE100** [comment]
are you on version 1.1.2? because items don't disappear anymore.
if so the "not letting you drop mask" is a config option you can set, it requires you to have x amount of full inventory slots before you can drop a mask, it's to prevent cheesing the system.
you can just set it to 0 to disable it.

**Comment by rogedkone** [comment]
V1.1.2
3 of 4 slots empty
Get mask and can't drop it.

**Comment by OE100** [comment]
by default you need to have 3 full (not empty) slots before you can drop a mask
