### ISSUE TITLE
v49 hand stuck, can't drop or interact with anything.

### ISSUE THREAD

**Issue by HamedAlmanthari** [OE100/PossessedMask#8]
hello. sometimes when i pickup something while the mask is in my inventory, my hands get stuck and i can't drop or interact with anything. the mask will switch the slot and possess me. i'm not sure if another mod is conflicting with this mod or not. this is what i get in the console when i get this bug. 
![image](https://github.com/OE100/PossessedMask/assets/133137232/ca0b1433-6b84-4d76-a5eb-5eaee4c04fbb)
and it just keeps spamming the same thing. i have log disk write disabled because of framedrops sorry.

**Comment by HamedAlmanthari** [comment]
i disabled Switch Slot Mechanic for the time being

**Comment by HamedAlmanthari** [comment]
also, this happens SOMETIMES. not everytime. i'm guessing it happens when i pickup something else and the mask changes my active slot at the same time.

**Comment by OE100** [comment]
uploaded version 2.0.0, check if it still happens and get back to me if it does.
sorry for the long wait, I didn't have free time.

**Comment by HamedAlmanthari** [comment]
great to hear! it's ok i understand.

**Comment by HamedAlmanthari** [comment]
it doesn't seem like the mod is working anymore. it's completely broken for me. idk if it's conflicting with some other mod or not but reverting back to v1.1.2 seems to work. i guess i'll use v1.1.2 for now.
