### ISSUE TITLE
v49 non-free hand slot stuck

### ISSUE THREAD

**Issue by LeoPeink** [OE100/PossessedMask#9]
After the mask changes active slot and possesses you, you are unable to climb stairs, open doors and interact with other stuff UNLESS you use a free hand.

**Comment by silencewebber** [comment]
Most frustratingly, this bug causes you to be unable to recharge walkies and flashlights. Oddly, I've quit out and rejoined a game where this happened to me and it didn't fix it. Sometimes dying or teleporting fixes it.

**Comment by OE100** [comment]
uploaded version 2.0.0, check if it still happens and get back to me if it does.
sorry for the long wait, I didn't have free time.
